language: java
jdk: oraclejdk8
sudo: false
script: gradle clean test integrationTest
before_script:
    - wget http://services.gradle.org/distributions/gradle-2.14.1-bin.zip
    - unzip gradle-2.14.1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-2.14.1
    - export PATH=$GRADLE_HOME/bin:$PATH